version: "3.8"
services:
  teams-recorder:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DISPLAY=:99
    shm_size: "1gb"
    volumes:
      - ./gravacoes:/app/gravacoes
    restart: always